version: "3.9"

services:
  frontend:
    image: hod284/monitoring-frontend:latest  # 실제 Docker Hub 이미지명으로 변경하세요
    container_name: monitoring-frontend
    ports:
      - "3000:80"
    restart: always